import { Inter } from "next/font/google";
import "./globals.css";
import connectDB from "@/utils/db/connectDB";

const inter = Inter({ subsets: ["latin"] });

// todo: remove when done with development
export const dynamic = "force-dynamic";

// variable to differentiate dev/prod environment when necessary app-wide
export const productionEnv = process.env.NODE_ENV === "production";

export const metadata = {
  title: "Xclusive Store",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
